let DB=null,watchId=null,tripStarted=null,lastPos=null,tripMeters=0,tripSpeeds=[],installPrompt=null,currentCoords=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=0)=>n==null?'—':Number(n).toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d});
const euro=n=>n==null?'—':Number(n).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
const dateFR=s=>s?new Date(s).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2700)}
function show(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('.bottom-nav [data-go]').forEach(x=>x.classList.toggle('selected',x.dataset.go===id));scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$$('.back').forEach(b=>b.onclick=()=>show('home'));
function tick(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}tick();setInterval(tick,1000);
async function load(){DB=await fetch('data/fiesta-data.json').then(r=>r.json());renderRoadTrip();loadSettings();}
function renderRoadTrip(){const s=DB.summary,v=DB.vehicle;$('#vehicleLine').textContent=`${v.name} • ${fmt(s.currentOdometer)} km`;$('#odo').textContent=fmt(s.currentOdometer)+' km';$('#avg').textContent=fmt(s.averageConsumption,1)+' L/100';$('#fuelSpend').textContent=euro(s.fuelSpend);$('#vOdo').textContent=fmt(s.currentOdometer)+' km';$('#vAvg').textContent=fmt(s.averageConsumption,1)+' L/100';$('#registration').textContent=v.registration||'—';$('#maintSpend').textContent=euro(s.maintenanceSpend);$('#maintCount').textContent=DB.maintenanceRecords.length;const rev=DB.maintenanceRecords.filter(x=>x.description.toLowerCase().includes('révision')).sort((a,b)=>b.date.localeCompare(a.date))[0];$('#lastService').textContent=rev?dateFR(rev.date):'—';$('#fuelList').innerHTML=DB.fuelRecords.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(x=>`<div class="list-item"><div><b>${dateFR(x.date)}</b><small>${x.location||x.fuel||'Carburant'}</small></div><div class="right"><b>${fmt(x.liters,2)} L</b><small>${euro(x.totalPrice)}${x.consumption?' • '+fmt(x.consumption,1)+' L/100':''}</small></div></div>`).join('');$('#maintList').innerHTML=DB.maintenanceRecords.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12).map(x=>`<div class="list-item"><div><b>${x.description}</b><small>${dateFR(x.date)}${x.location?' • '+x.location:''}</small></div><div class="right"><b>${x.cost?euro(x.cost):''}</b><small>${x.odometer?fmt(x.odometer)+' km':''}</small></div></div>`).join('')}
function loadSettings(){const s=JSON.parse(localStorage.getItem('fc-settings-v2')||'{}');if(s.driverName)$('#driverName').value=s.driverName;if(s.navChoice)$('#navChoice').value=s.navChoice;if(s.lbcUrl)$('#lbcUrl').value=s.lbcUrl;$('#driverGreeting').textContent=($('#driverName').value||'Florian').toUpperCase()}
$('#saveSettings').onclick=()=>{localStorage.setItem('fc-settings-v2',JSON.stringify({driverName:$('#driverName').value.trim()||'Florian',navChoice:$('#navChoice').value,lbcUrl:$('#lbcUrl').value.trim()}));$('#driverGreeting').textContent=($('#driverName').value||'Florian').toUpperCase();toast('Réglages enregistrés')};
function openUrl(url,fallback){location.href=url;if(fallback)setTimeout(()=>location.href=fallback,1100)}
function navUrl(q){const nav=$('#navChoice').value,encoded=encodeURIComponent(q||'');if(nav==='google')return encoded?`comgooglemaps://?q=${encoded}`:'comgooglemaps://';if(nav==='waze')return encoded?`https://waze.com/ul?q=${encoded}&navigate=yes`:'waze://';return encoded?`maps://?q=${encoded}`:'maps://'}
function action(a){const map={music:['music://'],podcasts:['podcasts://'],phone:['tel://'],spotify:['spotify://','https://open.spotify.com'],youtube:['youtubemusic://','https://music.youtube.com']};if(a==='maps'){openUrl(navUrl(''));return}if(a==='lbc'){location.href=$('#lbcUrl').value||'https://www.lbc.co.uk/radio/';return}const u=map[a];if(u)openUrl(u[0],u[1])}
$$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
$('#openDestination').onclick=()=>{const q=$('#destination').value.trim();if(!q)return toast('Saisissez une destination');location.href=navUrl(q)};
function hav(a,b){const R=6371000,p=Math.PI/180,dlat=(b.latitude-a.latitude)*p,dlon=(b.longitude-a.longitude)*p;const x=Math.sin(dlat/2)**2+Math.cos(a.latitude*p)*Math.cos(b.latitude*p)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function setNeedle(selector,gaugeSelector,speed){const max=160,clamped=Math.min(max,Math.max(0,speed)),deg=-130+(clamped/max)*260;$(selector).style.transform=`rotate(${deg}deg)`;$(gaugeSelector).style.setProperty('--speed-angle',`${(clamped/max)*260}deg`)}
function position(p){const c=p.coords,s=Math.max(0,(c.speed||0)*3.6);currentCoords={latitude:c.latitude,longitude:c.longitude};$('#gpsSpeed').textContent=Math.round(s);$('#tripSpeed').textContent=Math.round(s);setNeedle('#needle','#homeGauge',s);setNeedle('#tripNeedle','#tripGauge',s);const alt=c.altitude==null?'—':Math.round(c.altitude)+' m';$('#tripAltitude').textContent=alt;$('#homeAltitude').textContent=alt;if(tripStarted){if(lastPos){const d=hav(lastPos,currentCoords);if(d<250)tripMeters+=d}lastPos=currentCoords;tripSpeeds.push(s);updateTripUi()}}
if(navigator.geolocation)watchId=navigator.geolocation.watchPosition(position,()=>toast('Activez la localisation pour afficher la vitesse GPS.'),{enableHighAccuracy:true,maximumAge:2000,timeout:12000});
function updateTripUi(){const avg=tripSpeeds.reduce((a,b)=>a+b,0)/(tripSpeeds.length||1),km=tripMeters/1000;$('#tripDistance').textContent=fmt(km,2)+' km';$('#homeDistance').textContent=fmt(km,1)+' km';$('#tripAvgSpeed').textContent=Math.round(avg)+' km/h';$('#homeAvg').textContent=Math.round(avg)+' km/h'}
setInterval(()=>{if(!tripStarted)return;const sec=Math.floor((Date.now()-tripStarted)/1000),t=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');$('#tripDuration').textContent=t;$('#homeDuration').textContent=t},1000);
$('#tripToggle').onclick=()=>{if(!tripStarted){tripStarted=Date.now();tripMeters=0;tripSpeeds=[];lastPos=null;$('#tripToggle').textContent='Terminer le trajet';toast('Trajet démarré')}else{const arr=JSON.parse(localStorage.getItem('fc-trips-v2')||'[]');arr.unshift({date:new Date().toISOString(),distanceKm:tripMeters/1000,durationMs:Date.now()-tripStarted,avgSpeed:tripSpeeds.reduce((a,b)=>a+b,0)/(tripSpeeds.length||1)});localStorage.setItem('fc-trips-v2',JSON.stringify(arr));tripStarted=null;$('#tripToggle').textContent='Démarrer le trajet';toast('Trajet enregistré')}};
$('#csvImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;localStorage.setItem('fc-last-csv-v2',await f.text());toast('Export Road Trip importé localement')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();installPrompt=null}else toast('Dans Safari : Partager → Sur l’écran d’accueil')};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
load().catch(()=>toast('Impossible de charger les données Road Trip'));
